# This file is synced with stordco/common-config-elixir. Any changes will be overwritten.

name: Production

on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

concurrency:
  group: Production

jobs:
